### ISSUE TITLE
[Bug]: action='extend' in v0.2.0 breaks compatabilty with Python3 < 3.8

### ISSUE THREAD

**Issue by log1-c** [NETWAYS/check_vmware_nsxt#18]
### Please try to fill out as much of the information below as you can. Thank you!

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Which version contains the bug?

0.2.0

### Describe the bug

v0.2.0 introduced the exclude parameter which is defined with `action='extend'` in the code.
This renders the script unusable on systems having a Python3 version lower than 3.8, like RHEL8 for example.

### How to recreate the bug?

Download and execute v0.2.0 of the script on a system with Python3 lower than 3.8

**Comment by martialblog** [comment]
Hi, while I wouldn't call this a "bug" I do understand that it is inconvenient.

Since earlier versions than Python 3.8 are end-of-life and Python 3.8 should be available in the RHEL8 repos right now, I feel a bit reluctant to change the current code.

However, shouldn't be to much of a change, so we could have version without `action='extend'` on a "backport" branch.

@log1-c  Do you have code that is working for you?

**Comment by log1-c** [comment]
Thanks for the quick reply.
Wasn't shure if I should open it as a "bug" or more a "documentation",as I mostly meant it as an FYI. And I can understand if you are not willing to change the code!

I have switched back to a earlier version, as we currently don't use the exclude parameter.
Will also discuss internally if raising the Python3 version is an option.

**Comment by martialblog** [comment]
I'll update the README accordingly 

This should work on older versions, I tested it on Python 3.6: https://github.com/NETWAYS/check_vmware_nsxt/tree/backport

**Comment by martialblog** [comment]
README is updated on both branches. 

@log1-c can you confirm the code is working?

**Comment by log1-c** [comment]
yes, script from https://github.com/NETWAYS/check_vmware_nsxt/tree/backport works.
thank you!
